### ISSUE TITLE
提示文件找不到

### ISSUE THREAD

**Issue by mdjwanghong** [tencentyun/qcloud-sdk-ios#1]
提示如下文件找不到：
#import <QCloudCore/QCloudCore.h>

只能改成以下方式才可以：
#import "QCloudCore.h"

为什么？

**Comment by EricCheungSCUT** [comment]
因为我们开发时是在cocoapods环境下进行开发的，我们的基础库例如QCloudCore会先被编译成一个framework，所以我们在外部采用#import <QCloudCore/QCloudCore.h>这种语法去引入QCloudCore里的一个头文件是没有问题的。当然这是基于采用cocoapods集成我们SDK的情况，如果直接拖入代码的形式进行集成的话，就不会有QCloudCore这个框架存在，所以在外部采用这种语法去进行import就不行了。        
     
所以重点是，如果采取将我们打包好的.framework格式的SDK拖入工程，或者采用cocoapods集成SDK的话，#import <QCloudCore/QCloudCore.h>这种语法没有问题。如果直接拖入源码的话，需要采用#import "QCloudCore.h"的形式导入头文件

**Comment by mdjwanghong** [comment]
谢谢！
