### ISSUE TITLE
为什么会先执行setFinishBlock， setFinishBlock完成之后    过很久才执行setDownProcessBlock

### ISSUE THREAD

**Issue by ArthurCL** [tencentyun/qcloud-sdk-ios#10]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？

云对象存储

* 您使用的SDK版本好是多少？

5.5.8

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]

真机和模拟器都有   9.2.1和12.1 wifi

* 使用更高版本的SDK是否解决了您的问题？
没有

* 这个问题是否和特定的网络环境有关系？

不确定

* 您集成我们SDK的方式是什么？

cocoapods

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

QCloudGetObjectRequest* request = [QCloudGetObjectRequest new];
  //设置下载的路径 URL，如果设置了，文件将会被下载到指定路径中
  request.downloadingURL = [NSURL URLWithString:QCloudTempFilePathWithExtension(@"downding")];
  request.object = @“您的Object-Key”;
  request.bucket = @"test-123456789";
[request setDownProcessBlock:^(int64_t bytesDownload, int64_t totalBytesDownload, int64_t totalBytesExpectedToDownload) {
     //下载过程中的进度
    }];

[request setFinishBlock:^(id outputObject, NSError \*error) {
    //additional actions after finishing
}];

[[QCloudCOSXMLService defaultCOSXML] GetObject:request];

为什么会先执行setFinishBlock， setFinishBlock完成之后    过很久才执行setDownProcessBlock

**Comment by 15809284891** [comment]
![image](https://user-images.githubusercontent.com/17779724/51507033-dd7d9c80-1e29-11e9-92de-af2f16e57700.png)
这边我试了5.5.8，是先进行进度回调然后再setfinish的呢
![image](https://user-images.githubusercontent.com/17779724/51507066-04d46980-1e2a-11e9-9c42-c979c8ea0d70.png)

**Comment by 15809284891** [comment]
是之前的版本都有这个问题呢，还是只有5.5.8呢

**Comment by 15809284891** [comment]
先关掉，后面有问题可以再打开

**Comment by 15809284891** [comment]
先关掉，后面有问题可以再打开
