### ISSUE TITLE
上传过程中MD5校验与本地不一致，返回的etag长度超过32

### ISSUE THREAD

**Issue by zxjay** [tencentyun/qcloud-sdk-ios#11]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
上传文件QCloudCOSXMLUploadObjectRequest
* 您使用的SDK版本好是多少？
5.5.8
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
模拟器，wifi环境
* 使用更高版本的SDK是否解决了您的问题？
已经用最高版本了
* 这个问题是否和特定的网络环境有关系？
没
* 您集成我们SDK的方式是什么？
pod
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

上传文件，需要分片时，会出现下面的错误。
当前网络环境为2 请求失败Error Domain=com.tencent.qcloud.networking Code=20004 "DataIntegrityError分片:上传过程中MD5校验与本地不一致，请检查本地文件在上传过程中是否发生了变化,建议调用删除接口将COS上的文件删除并重新上传,本地计算的 MD5 值:90d440f5e95ecc71f804749b4425ef67, 返回的 ETag值:8ad46ffa98077830d165a747f742e74f08a02ab3, Request id:NWM2NTRlMDJfZGEyOTVkNjRfNzMzMF85ZjJmNWM=" UserInfo={NSLocalizedDescription=DataIntegrityError分片:上传过程中MD5校验与本地不一致，请检查本地文件在上传过程中是否发生了变化,建议调用删除接口将COS上的文件删除并重新上传,本地计算的 MD5 值:90d440f5e95ecc71f804749b4425ef67, 返回的 ETag值:8ad46ffa98077830d165a747f742e74f08a02ab3, Request

**Comment by 15809284891** [comment]
您好，这边排查到的情况如下：
原因：
 1. 如果开了白名单cos上存的就是sha。没开存的就是md5。
 2. 但是SDK在一个分片上传完成之后，是计算出一个MD5与服务器返回的etag进行比对，不一致会出现这个原因，由于您开启了白名单，所以报错了。
解决:可以通过将QCloudCOSXMLUploadRequest的enableMD5Verification 的属性设置为NO，将其关闭。
