### ISSUE TITLE
cocoapods 1.7.1 问题

### ISSUE THREAD

**Issue by butcheryl** [tencentyun/qcloud-sdk-ios#13]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？

* 您使用的SDK版本好是多少？

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]

* 使用更高版本的SDK是否解决了您的问题？

* 这个问题是否和特定的网络环境有关系？

* 您集成我们SDK的方式是什么？

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

## 问题描述
cocoapod 1.7.0 支持 Multiple Pod Projects，开启这个功能后在 Swift 工程中，编译会报无法找到头文件的错误，具体头文件为：

```
QualityDataUploader.m
#import "NSError+QCloudNetworking.h"

QCloudCOSXMLService.m
#import "UIDevice+QCloudFCUUID.h"

QCloudCOSXMLUploadObjectRequest.m
#import "QCloudSupervisoryRecord.h"
#import "QCloudUniversalPath.h"
#import "QCloudSandboxPath.h"
#import "QCloudMediaPath.h"
#import "QCloudBundlePath.h"

QCloudCOSTransferMangerService.m
#import "QCloudThreadSafeMutableDictionary.h"
```

上面所有头文件更改成 `<QCloudCore/xxx.h>`形式，编译成功！

## 例子
* Swift 工程
* cocoapods 版本 1.7.1 
* Podfile 文件内容
```
install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesktopDemp
  pod 'QCloudCOSXML'
end
```

**Comment by 15809284891** [comment]
您说的是将源码中的改成<QCloudCore/xxx.h>，还是在代码中使用的时候呢

**Comment by butcheryl** [comment]
@15809284891 源码

**Comment by 15809284891** [comment]
感谢反馈，5.6.2已经修复，可以是用最新的sdk版本
