### ISSUE TITLE
SwiftCompiler Warning

### ISSUE THREAD

**Issue by leacode** [tencentyun/qcloud-sdk-ios#15]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
对象存储

* 您使用的SDK版本好是多少？
5.6.4

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机iOS11，xcode10，Swift5

* 使用更高版本的SDK是否解决了您的问题？
否

* 这个问题是否和特定的网络环境有关系？
否

* 您集成我们SDK的方式是什么？
pods

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

出现超多SwiftCompiler Warning
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

因为Swift bridge使用OC的时候，需要OC代码做一些空类型的指定，会使代码更安全，希望能够优化一下这方面的代码。

另外建议提供Swift的demo，只是建议。

**Comment by 15809284891** [comment]
好的，感谢您的反馈，更新之后会在这里同步

**Comment by 15809284891** [comment]
您好，感谢您的反馈,5.6.7修复了编译警告，并且提供了swift版本的demo https://github.com/tencentyun/qcloud-sdk-ios-samples/tree/master/QCloudCOSXMLSwfitDemo

**Comment by 15809284891** [comment]
请集成5.6.9或者5.6.9以上的sdk，编译问题已修复
