### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by mistdon** [tencentyun/qcloud-sdk-ios#16]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
QCloudCOSXML 图片上传和下载服务

* 您使用的SDK版本好是多少？
QCloudCOSXML 5.6.2
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
模拟器，iOS12.2 WIFI
* 使用更高版本的SDK是否解决了您的问题？
使用最新版本
* 这个问题是否和特定的网络环境有关系？
无
* 您集成我们SDK的方式是什么？
Pod
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

从JSON API迁移到XML API
使用服务端返回的签名信息Sign，bucket = < bucketName-Appid >, region="ap-shanghai"

- (void) signatureWithFields:(QCloudSignatureFields*)fileds
                     request:(QCloudBizHTTPRequest*)request
                  urlRequest:(NSMutableURLRequest*)urlRequst
                   compelete:(QCloudHTTPAuthentationContinueBlock)continueBlock{
    QCloudSignature *signature = [QCloudSignature signatureWithMaxExpiration: @"服务端返回的Sign"];
}
显示错误信息：
Error Domain=com.tencent.qcloud.networking Code=403 "(null)" UserInfo={__name=Error, RequestId=NWQ0N2E1MWRfNjE5ZDA4MDlfYWU5Y19iNGRkOTk=, StringToSign=sha1
1564976412;1564980012
009ec928a0a91a0cc0c936c7acddc10169a45e33, Code=SignatureDoesNotMatch, TraceId=OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjYjdkMDE0YzdiNDU3MThiMzQ3NzBkMmQwZjE1ZWVlZmU=, FormatString=put
/38905642349559468_1.jpg, Resource=xxxx, Message=The Signature you specified is invalid.}

**Comment by 15809284891** [comment]
是服务端返回的签名不对，建议服务端检查下SecretId是否填写正确

**Comment by 15809284891** [comment]
用户太就2未回复，暂时关闭

**Comment by LiuQiang11** [comment]
QCloudCOSXML音频上传
QCloudCOSXML 5.7.1
设备：真机 iOS9.3.1 WIFI 4G
集成方式pod
[Error][QCloudCOSXMLUploadObjectRequest][3348]当前网络环境为2 请求失败Error Domain=com.tencent.qcloud.networking Code=403 "(null)" UserInfo={__name=Error, RequestId=NWViZTE4OGVfMjliYzFjMDlfMTg0YzZfNTBlMTNl, Code=AccessDenied, ServerTime=2020-05-15T04:20:30Z, TraceId=OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNmRkZmRhYjdmMTRlZWE2NGNjZDk3YTk1ODc0ZDk2ZjI=, Resource=xbapp-10076982.cos.ap-shanghai.myqcloud.com/1589516430_app2_3wfadlzxpmczkn90ru.mp3, Message=Request has expired}

**Comment by LiuQiang11** [comment]
升级为最新版也报错
