### ISSUE TITLE
overrides method warning！！！

### ISSUE THREAD

**Issue by AsTao** [tencentyun/qcloud-sdk-ios#17]
ld: warning: instance method 'modelCustomWillTransformFromDictionary:' in category from /x/QCloudCOSXML(QCloudListAllMyBucketsResult+CustomModelTransfer.o) overrides method from class in /x/QCloudCOSXML.framework/QCloudCOSXML(QCloudListAllMyBucketsResult.o)

**Comment by 15809284891** [comment]
已修复

**Comment by 15809284891** [comment]
您好，感谢您的反馈,5.6.7已修复

**Comment by 15809284891** [comment]
已修复
