### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by wxlpp** [tencentyun/qcloud-sdk-ios#19]
QCloudCOSXML中
`#import <QCLOUDRestNet.h>`应统一改为
`#import <QCloudCore/QCLOUDRestNet.h>`

**Comment by 15809284891** [comment]
是那个版本的sdk呢

**Comment by wxlpp** [comment]
> 是那个版本的sdk呢

5.6.9 xcode11 Swift cocopods

**Comment by 15809284891** [comment]
这边测试没有复现，swift demo也可以正常使用的，能简单提供一个复现demo吗

**Comment by wxlpp** [comment]
QCLOUDRestNet.h是在QCloudCore包内的 ，QCloudCOSXML项目中别的地方对 QCloudCore 包内头文件的引用都是 `#import <QCloudCore/*.h>` 只有这里不是。这种写法本身就是不对的，不用复现就能发现。
当你启用 cocopods generate_multiple_pod_projects 的时候问题就会出现。

**Comment by 15809284891** [comment]
嗯呢，好的，感谢反馈

**Comment by 15809284891** [comment]
您好,5.7.1修复

**Comment by 15809284891** [comment]
已修复
