### ISSUE TITLE
pod 'QCloudCOSXML', '~>5.0.0' 找不到

### ISSUE THREAD

**Issue by mdjwanghong** [tencentyun/qcloud-sdk-ios#2]
pod 'QCloudCOSXML', '~>5.0.0' 找不到

**Comment by mdjwanghong** [comment]
[!] Unable to find a specification for `QCloudCOSXML (~> 5.0.0)`

**Comment by EricCheungSCUT** [comment]
这是因为本地的spec配置信息没有更新，请执行 `pod repo update`后，再运行`pod install`

**Comment by mdjwanghong** [comment]
可以了，谢谢！
