### ISSUE TITLE
Pod依赖没有固定，导致5.7.0老版本编译出错

### ISSUE THREAD

**Issue by welkiner** [tencentyun/qcloud-sdk-ios#20]
![图片](https://user-images.githubusercontent.com/5791830/72128195-0c7b7e00-33ad-11ea-97d6-34aacc6d78a2.png)

**Comment by 15809284891** [comment]
感谢反馈，版本更新之后会在这里同步

**Comment by 15809284891** [comment]
感谢您的反馈，5.7.2已修复
