### ISSUE TITLE
QCloudNewCOSV4 和 FCUUID 编译报错

### ISSUE THREAD

**Issue by happy201993** [tencentyun/qcloud-sdk-ios#21]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
QCloudNewCOSV4

* 您使用的SDK版本好是多少？
5.3.2

* 使用更高版本的SDK是否解决了您的问题？
我们必须使用v4 不能使用xml。xml没有这个问题。

* 您集成我们SDK的方式是什么？
cocoapods

**Comment by 15809284891** [comment]
具体报错信息可以贴一下吗，本地没有复现这种情况，线上的demo也没有复现呢https://github.com/tencentyun/qcloud-sdk-ios-samples

**Comment by happy201993** [comment]
[testPod.zip](https://github.com/tencentyun/qcloud-sdk-ios/files/4082230/testPod.zip)跑一下这个

**Comment by 15809284891** [comment]
QCloudFCUUID 其实就是FCUUID，这里我会修复 下不过这里建议您用v5呢，v4已经不维护了，修复了更新的也是v5呢

**Comment by 15809284891** [comment]
https://cloud.tencent.com/document/product/436/11280

**Comment by 15809284891** [comment]
由于客户长时间未回复，先关闭
