### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by WHDevLab** [tencentyun/qcloud-sdk-ios#22]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
腾讯COS  iOS SDK

* 您使用的SDK版本好是多少？
QCloudCOSXML(5.7.5)
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
iPhone Xs 13.5.1
* 使用更高版本的SDK是否解决了您的问题？
没有
* 这个问题是否和特定的网络环境有关系？
没有
* 您集成我们SDK的方式是什么？
cocospods
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
file:QCloudOperationQueue.m
line:[self->_runningOperationArray addObject:operation]; 
crash because operation is nil

**Comment by 15809284891** [comment]
5.7.6已修复

**Comment by 15809284891** [comment]
用户长时间未回复暂时关闭
