### ISSUE TITLE
创建 COS 服务实例 fenceQueue:requestCreatorWithContinue: 委托不调用

### ISSUE THREAD

**Issue by y0unghe** [tencentyun/qcloud-sdk-ios#28]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
COS

* 您使用的SDK版本好是多少？
5.8.1
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机
* 使用更高版本的SDK是否解决了您的问题？
否
* 这个问题是否和特定的网络环境有关系？
否
* 您集成我们SDK的方式是什么？
Cocoapods
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        let config = QCloudServiceConfiguration.init();
        config.appID = "test id";
        
        let endpoint = QCloudCOSXMLEndPoint.init();
        //服务地域简称，例如广州地区是 ap-guangzhou
        endpoint.regionName = "ap-hongkong";
        // 使用 HTTPS
        endpoint.useHTTPS = true;
        config.endpoint = endpoint;
        // 密钥提供者为自己
        config.signatureProvider = self;
        
        // 初始化 COS 服务示例
        QCloudCOSXMLService.registerDefaultCOSXML(with: config);
        QCloudCOSTransferMangerService.registerDefaultCOSTransferManger(
            with: config);
        
        // 初始化临时密钥脚手架
        self.credentialFenceQueue = QCloudCredentailFenceQueue.init();
        self.credentialFenceQueue?.delegate = self;
        
        return true
    }`

QCloudCredentailFenceQueueDelegate 和 QCloudSignatureProvider2委托的方法，打断点都没有进来。不知道是哪里的问题。

**Comment by 15809284891** [comment]
您的问题可参考该文档解决哈://cloud.tencent.com/document/product/436/50747

**Comment by 15809284891** [comment]
由于客户长时间未回复，暂时关闭
