### ISSUE TITLE
experationDate单词拼写错误

### ISSUE THREAD

**Issue by erpapa** [tencentyun/qcloud-sdk-ios#29]
类名：QCloudCredential
属性：experationDate
链接：[https://github.com/tencentyun/qcloud-sdk-ios/tree/master/QCloudCore/Classes/Base/QCloudClientBase/Authentation/QCloudCredential.h](https://github.com/tencentyun/qcloud-sdk-ios/tree/master/QCloudCore/Classes/Base/QCloudClientBase/Authentation/QCloudCredential.h)

**Comment by 15809284891** [comment]
已修复
