### ISSUE TITLE
Apple M1 适配

### ISSUE THREAD

**Issue by vencewill** [tencentyun/qcloud-sdk-ios#30]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
> 适配升级

* 您使用的SDK版本好是多少？
> 5.8.4

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
> Apple M1 MacBook Pro

* 使用更高版本的SDK是否解决了您的问题？
> 否

* 这个问题是否和特定的网络环境有关系？
> 否

* 您集成我们SDK的方式是什么？
> Pod

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

> 在 M1 上，运行即可

core 的 Podspec 中的
```ruby
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```
虽然可以解决 Intel 上 Xcode 12 模拟器的问题，但是 M1 上 arm 架构的模拟器没有得到实质解决（非 Rosetta 环境）。
希望尽快可以适配。

祝好。

**Comment by HuRKun** [comment]
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
这个需要配置在哪里？

**Comment by wangbo1185742894** [comment]
Xcode->product->destination->destination achitectures->show rosetta destinations,这时模拟器会处于兼容x86_64架构模式 试试这样。
