### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by arlins** [tencentyun/qcloud-sdk-ios#32]
错误：
`ld: framework not found QCloudCOSXML
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

环境：Xcode 11.6，CocoaPods 1.10.1
podfile：pod 'QCloudCOSXML', '~> 5.8.1'

构建失败，提示无法成功链接QCloud相关的库（实际是没有成功生成QCloud相关的库），官方Demo也是构建失败：https://github.com/tencentyun/qcloud-sdk-ios

**Comment by 15809284891** [comment]
麻烦您清理下编译缓存看看哈，我们这边没有复现呢
