### ISSUE TITLE
QCloudHTTPSessionManager类中- (void)executeRestHTTPReqeust:(QCloudHTTPRequest *)httpRequest 中stringByReplacingOccurrencesOfString参数nil崩溃

### ISSUE THREAD

**Issue by holiny** [tencentyun/qcloud-sdk-ios#35]
![image](https://user-images.githubusercontent.com/17294005/122356110-0ff13c80-cf85-11eb-89a8-e34c4d0913b1.png)

NSString *host = [[task.currentRequest.URL.absoluteString stringByReplacingOccurrencesOfString:task.currentRequest.URL.scheme
                                                                                        withString:@""] stringByReplacingOccurrencesOfString:@"://"
                                                                                                                                  withString:@""];

请帮助修复崩溃问题，谢谢

**Comment by 15809284891** [comment]
5.9.1已修复
