### ISSUE TITLE
QCloudQCloudCOSXMLLoad 的load方法影响App启动

### ISSUE THREAD

**Issue by owenwangsp** [tencentyun/qcloud-sdk-ios#36]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
云服务

* 您使用的SDK版本好是多少？
5.9.3

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
iPhone7

* 使用更高版本的SDK是否解决了您的问题？
已经是最新版本

* 这个问题是否和特定的网络环境有关系？
无关

* 您集成我们SDK的方式是什么？
pod集成

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
与网络无关

QCloudQCloudCOSXMLLoad 的load方法会影响App的启动，根据我的测试在iPhone7上冷启动大概在主线程中耗时82ms，希望能延后load中初始化方法，或者交给开发者来初始化

**Comment by gratefulHeart** [comment]
这个影响启动速度的问题是哪个版本有优化吗？
