### ISSUE TITLE
NSError (QualityDataUploader) - (NSDictionary *)toUploadEventParamters  crash cause NSDictionary attempt to insert nil 

### ISSUE THREAD

**Issue by holiny** [tencentyun/qcloud-sdk-ios#37]
![image](https://user-images.githubusercontent.com/17294005/127445029-95940ae9-558f-47ec-ac8b-251dfe1d70d8.png)

类@implementation NSError (QualityDataUploader)中方法- (NSDictionary *)toUploadEventParamters，尝试将nil插入dictionary，请加一个非nil判断，帮助修复，谢谢

**Comment by 15809284891** [comment]
最新版本6.0.5已修复，辛苦升级一下哈
