### ISSUE TITLE
cocoapods 集成 build失败"QualityDataUploader.h" not found 

### ISSUE THREAD

**Issue by kb100824** [tencentyun/qcloud-sdk-ios#39]
pod 'QCloudCOSXML' '5.9.4'  编译报错，需要手动修改头文件引入方式 比如这样：
`#import <QCloudCore/QualityDataUploader.h>`
 这种方式不可取。希望发布新版本修复这个问题

**Comment by wangbo1185742894** [comment]
最新版本5.9.5已修改，最新版本6.0.5
