### ISSUE TITLE
BeaconAsyncSocket相关崩溃

### ISSUE THREAD

**Issue by oliver102** [tencentyun/qcloud-sdk-ios#42]
为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。
您使用的是我们的哪一种服务？
QCloudCOSXML

您使用的SDK版本好是多少？
5.9.9

您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
iPhone13,, iOS 15.1.1, wifi  和机型没什么关系，别的机型也有

这个问题是否和特定的网络环境有关系？
无

您集成我们SDK的方式是什么？
pod

备注：iOS15以下的系统没这个问题

CrashDoctor Diagnosis: Attempted to dereference garbage pointer 0x20.

Thread 31 Crashed:
0   libobjc.A.dylib                     0x000000019a0bebf0 objc_release
1   Foundation                          0x00000001832233e4 __NSThreadPerformPerform
2   CoreFoundation                      0x0000000181a7f020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
3   CoreFoundation                      0x0000000181a8fce0 __CFRunLoopDoSource0
4   CoreFoundation                      0x00000001819ca054 __CFRunLoopDoSources0
5   CoreFoundation                      0x00000001819cf7f4 __CFRunLoopRun
6   CoreFoundation                      0x00000001819e33b8 CFRunLoopRunSpecific
7   Foundation                          0x00000001831fe354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
8   FXApp                               0x0000000104ae08b4 +[BeaconAsyncSocket cfstreamThread]
9   Foundation                          0x000000018324e36c __NSThread__start__
10  libsystem_pthread.dylib             0x00000001f25e69a4 _pthread_start

**Comment by wangbo1185742894** [comment]
麻烦升级到最新版本试一下
