### ISSUE TITLE
Xcode 13打的开发证书包，初始化时uuidsOfUserDevices_iCloudInit崩溃

### ISSUE THREAD

**Issue by simpleease** [tencentyun/qcloud-sdk-ios#45]
App一启动就崩溃。Xcode连接真机调试不会崩溃，用开发证书打包安装运行就崩。

崩溃信息如下:

xception Type:  EXC_GUARD
Exception Subtype: GUARD_TYPE_USER
Exception Message: namespc 18 reason_code 0x0000000000000002
Exception Codes: 0x6000000000000012, 0x0000000000000002
Exception Note:  SIMULATED (this is NOT a crash)
Termination Reason: LIBSYSTEM; [2]

Triggered by Thread:  0

Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1b81b0ae8 os_fault_with_payload + 8
1   libsystem_trace.dylib         	       0x19b5b71b8 _os_log_impl_flatten_and_send + 7716
2   libsystem_trace.dylib         	       0x19b5b3b74 _os_log + 148
3   libsystem_trace.dylib         	       0x19b5bbcb0 _os_log_fault_impl + 24
4   SyncedDefaults                	       0x1acd7bc90 -[SYDRemotePreferencesSource initWithApplicationID:storeID:shared:additionalSource:containerPath:storeType:].cold.1 + 52
5   SyncedDefaults                	       0x1acd6e210 -[SYDRemotePreferencesSource initWithApplicationID:storeID:shared:additionalSource:containerPath:storeType:] + 1400
6   Foundation                    	       0x1824b05c8 -[NSUbiquitousKeyValueStore initWithBundleIdentifier:storeIdentifier:additionalStore:storeType:] + 348
7   Foundation                    	       0x18249363c __41+[NSUbiquitousKeyValueStore defaultStore]_block_invoke + 24
8   libdispatch.dylib             	       0x1808c3670 _dispatch_client_callout + 20
9   libdispatch.dylib             	       0x1808c4f18 _dispatch_once_callout + 32
10  Foundation                    	       0x18249ae38 +[NSUbiquitousKeyValueStore defaultStore] + 64
11  MyApp                   	       0x103280c9c -[QCloudFCUUID uuidsOfUserDevices_iCloudInit] + 12405916 (QCloudFCUUID.m:0)
12  MyApp                   	       0x1032801d0 -[QCloudFCUUID init] + 12403152 (QCloudFCUUID.m:48)
13  MyApp                   	       0x103280174 __30+[QCloudFCUUID sharedInstance]_block_invoke + 12403060 (QCloudFCUUID.m:31)
14  libdispatch.dylib             	       0x1808c3670 _dispatch_client_callout + 20
15  libdispatch.dylib             	       0x1808c4f18 _dispatch_once_callout + 32
16  MyApp                   	       0x103280154 +[QCloudFCUUID sharedInstance] + 12403028 (QCloudFCUUID.m:30)
17  MyApp                   	       0x1032817d8 +[QCloudFCUUID uuidForDevice] + 12408792 (QCloudFCUUID.m:0)

**Comment by wangbo1185742894** [comment]
https://developer.apple.com/forums/thread/691334 ，尝试升级一下xcode

**Comment by iPermanent** [comment]
Exception Note: SIMULATED (this is NOT a crash) 已经说明了这个不是一个crash
