### ISSUE TITLE
[QCloudCOSXMLService PutObject:]: unrecognized selector sent to instance 0x282e5d940

### ISSUE THREAD

**Issue by sleeppotato** [tencentyun/qcloud-sdk-ios#46]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
* oss

* 您使用的SDK版本好是多少？
* pod 'QCloudCOSXML', '~> 5.9.9'

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
* 真机

* 使用更高版本的SDK是否解决了您的问题？
* 更新到最新版本仍会因为私有方法引起crash

* 这个问题是否和特定的网络环境有关系？
* 没有

* 您集成我们SDK的方式是什么？
* cocoapods

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
* other linker flags 已添加 -ObjC

**Comment by 15809284891** [comment]
辛苦您再加下加上all_load看看呢
