### ISSUE TITLE
COS文件上传后，再调用getObjectMetadata，得到的Etag有误

### ISSUE THREAD

**Issue by lalinking** [tencentyun/qcloud-sdk-ios#47]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
COS 云存储
* 您使用的SDK版本号是多少？
5.6.23
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机,wifi
* 使用更高版本的SDK是否解决了您的问题？
否
* 这个问题是否和特定的网络环境有关系？
无
* 您集成我们SDK的方式是什么？
maven
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
文件是通过 spark 直接导入到 cosn://buc-13424123/key1/da/pp1/part-00000-f124f8f4-5b44-4c83-aece-6cd20629860b-c000.snappy.parquet
获取到的 ETag 为：001a387d4ca31d1952d3409c63503c71-3
得到的 ETag 位数超过32位，后面的 “-3” 去掉也不是正确的校验值。

**Comment by wangbo1185742894** [comment]
您的项目是ios 吗？
