### ISSUE TITLE
self.runOnService = nil

### ISSUE THREAD

**Issue by WANGNEWMAN** [tencentyun/qcloud-sdk-ios#5]
2018-05-25 15:55:23.299285+0800 RoWrite[3656:1418626] *** Assertion failure in -[QCloudGetObjectRequest prepareInvokeURLRequest:error:], /*****/Pods/QCloudCore/QCloudCore/Classes/QCloudClientBase/Request/QCloudBizHTTPRequest.m:108

使用腾讯云SDK下载、上传图片的时候出现；
在断言处崩溃 QCloudBizHTTPRequest中108行 NSAssert(self.runOnService, @"RUN ON SERVICE is nil%@", self.runOnService);这个地方

**Comment by EricCheungSCUT** [comment]
这个问题是在什么接口情况下出现的呢

**Comment by EricCheungSCUT** [comment]
还有就是，每次 GetObject 时是通过 
~~~
[[QCloudCOSXMLService defaultCOSXML]  GetObject:getObjectRequest]
~~~
去调用的吗，还是通过自定义的服务 
```Objective-C
[[QCloudCOSXMLService cosxmlServiceForKey:@"custom-service-key"] GetObject:getObjectRequest]
```



   

希望如果可以提供一个可以复现这个问题的 Demo 或者代码片段，这个可以帮助我们更快的帮忙解决这个问题

**Comment by EricCheungSCUT** [comment]
Close because of inactive for a long time
