### ISSUE TITLE
腾讯云和腾讯地图sdk引用相同文件冲突

### ISSUE THREAD

**Issue by bingolib** [tencentyun/qcloud-sdk-ios#50]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？

* 您使用的SDK版本好是多少？

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]

* 使用更高版本的SDK是否解决了您的问题？

* 这个问题是否和特定的网络环境有关系？

* 您集成我们SDK的方式是什么？

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

duplicate symbol '_qimeiClassMethodRecord' in:
    /Users/ll/Desktop/llr-ios/Pods/Tencent-MapSDK/sdk/QMapFoundationKit.framework/QMapFoundationKit(QimeiUtil.o)
    /Users/ll/Desktop/llr-ios/Pods/QCloudCore/QCloudCore/Classes/BeaconFramework/QimeiSDK.framework/QimeiSDK(QimeiUtil.o)
duplicate symbol '_qimeiAddClassOriginMethod' in:
    /Users/ll/Desktop/llr-ios/Pods/Tencent-MapSDK/sdk/QMapFoundationKit.framework/QMapFoundationKit(QimeiUtil.o)
    /Users/ll/Desktop/llr-ios/Pods/QCloudCore/QCloudCore/Classes/BeaconFramework/QimeiSDK.framework/QimeiSDK(QimeiUtil.o)
duplicate symbol '_qimeiCheckClassMethodHasReplaced' in:
    /Users/ll/Desktop/llr-ios/Pods/Tencent-MapSDK/sdk/QMapFoundationKit.framework/QMapFoundationKit(QimeiUtil.o)
    /Users/ll/Desktop/llr-ios/Pods/QCloudCore/QCloudCore/Classes/BeaconFramework/QimeiSDK.framework/QimeiSDK(QimeiUtil.o)
duplicate symbol '_QimeiCloudSettingKeyConifgVersion' in:
    /Users/ll/Desktop/llr-ios/Pods/Tencent-MapSDK/sdk/QMapFoundationKit.framework/QMapFoundationKit(QimeiCloudSetting.o)
    /Users/ll/Desktop/llr-ios/Pods/QCloudCore/QCloudCore/Classes/BeaconFramework/QimeiSDK.framework/QimeiSDK(QimeiCloudSetting.o)
duplicate symbol '_QimeiStorageKeyIdfv' in:
    /Users/ll/Desktop/llr-ios/Pods/Tencent-MapSDK/sdk/QMapFoundationKit.framework/QMapFoundationKit(QimeiStorage.o)
    /Users/ll/Desktop/llr-ios/Pods/QCloudCore/QCloudCore/Classes/BeaconFramework/QimeiSDK.framework/QimeiSDK(QimeiStorage.o)
duplicate symbol '_QimeiStorageKeyQimeiJson' in:
    /Users/ll/Desktop/llr-ios/Pods/Tencent-MapSDK/sdk/QMapFoundationKit.framework/QMapFoundationKit(QimeiStorage.o)
    /Users/ll/Desktop/llr-ios/Pods/QCloudCore/QCloudCore/Classes/BeaconFramework/QimeiSDK.framework/QimeiSDK(QimeiStorage.o)
ld: 6 duplicate symbols for architecture arm64

**Comment by wangbo1185742894** [comment]
可以使用精简版sdk，来剔除qimei。具体方式：若是pod方式集成sdk，可以使用 pod  'QCloudCOSXML/Slim' 。若是直接依赖的framework，可以吧qimei、beacon 两个sdk删除。

**Comment by bingolib** [comment]
> 可以使用专业版dk，来剔除qimei。具体方式：除pod方式集成sdk，可以使用pod 'QCloudCOSXML/Slim'。如果直接依赖的框架，可以去除qimei、beacon两个sdk。

感谢。替换为精简版已解决此问题。
