### ISSUE TITLE
M1 报错：framework not found QCloudCOSXML

### ISSUE THREAD

**Issue by bangjier** [tencentyun/qcloud-sdk-ios#51]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
* 对象存储

* 您使用的SDK版本好是多少？
* 6.1.0

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
* Apple M1 Max MacBook Pro，模拟器，iOS 15.5

* 使用更高版本的SDK是否解决了您的问题？
* 否

* 这个问题是否和特定的网络环境有关系？
* 否

* 您集成我们SDK的方式是什么？
* 使用 Cocoapods 集成
* pod 'QCloudCOSXML'
* 使用精简版也无法解决，报一样的错误信息
pod 'QCloudCOSXML/Transfer'

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

**Comment by wangbo1185742894** [comment]
demo在 m1上 执行pod install 后 可以正常运行么

**Comment by wangbo1185742894** [comment]
Xcode->product->destination->destination achitectures->show rosetta destinations,这时模拟器会处于兼容x86_64架构模式，试试这样
