### ISSUE TITLE
iOS16.2及以上系统 [BeaconAsyncSocket closeWithError:] crash

### ISSUE THREAD

**Issue by wanshanhu79** [tencentyun/qcloud-sdk-ios#54]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
 智聆语音评测
 pod 'TIWLogger_iOS', '1.0.1.41'

* 您使用的SDK版本好是多少？
  pod 'QCloudCOSXML', '6.1.9'
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
 真机，iOS16.2及以上系统
* 使用更高版本的SDK是否解决了您的问题？
 从 6.0.3 升级到6.1.9无解决，且更新说明中没有相关信息
* 这个问题是否和特定的网络环境有关系？
 否
* 您集成我们SDK的方式是什么？
 pod库
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
  
#15 Thread
libsystem_platform.dylib
__os_unfair_lock_recursive_abort + 36
libsystem_platform.dylib
__os_unfair_lock_lock_slow + 276 
CoreFoundation _CFSocketInvalidate + 128
CFNetwork __CFNetworkErrorGetLocalizedDescription + 295072
CoreFoundation _CFArrayApplyFunction + 68
CFNetwork __CFNetworkErrorGetLocalizedDescription + 183016
CoreFoundation __CFRelease + 356
CoreFoundation _CFSocketInvalidate + 1012
CFNetwork __CFNetworkErrorGetLocalizedDescription + 169104
CoreFoundation __CFStreamClose + 104
**** -[BeaconAsyncSocket closeWithError:] + 260
**** -[BeaconAsyncSocket doReadEOF] + 360
**** ___69-[BeaconAsyncSocket setupReadAndWriteSourcesForNewlyConnectedSocket:]_block_invoke + 88
libdispatch.dylib __dispatch_client_callout + 16
libdispatch.dylib __dispatch_continuation_pop$VARIANT$armv81 + 436
libdispatch.dylib __dispatch_source_invoke$VARIANT$armv81 + 1552
libdispatch.dylib __dispatch_lane_serial_drain$VARIANT$armv81 + 308
libdispatch.dylib __dispatch_lane_invoke$VARIANT$armv81 + 380
libdispatch.dylib __dispatch_workloop_worker_thread + 612
libsystem_pthread.dylib __pthread_wqthread + 284

**Comment by wangbo1185742894** [comment]
最新版本已经修复这个问题，也可以试着使用不含灯塔sdk的cos   QCloudCOSXML/Slim
