### ISSUE TITLE
QCloudCOSXML 5.8.9版本[BeaconAsyncSocket cfstreamThread]崩溃

### ISSUE THREAD

**Issue by arlins** [tencentyun/qcloud-sdk-ios#55]
pod 'QCloudCOSXML', '~> 5.8.1'，pod安装的是5.8.9版本。

是从5.8.1升级到5.8.9产生崩溃，影响用户非常多，iPad和iPhone用户均有，请处理。

堆栈如下：
Crashed: BeaconAsyncSocket-CFStream
0  libobjc.A.dylib                0x2d20 objc_release + 16
1  Foundation                     0x434c4 -[_NSThreadPerformInfo dealloc] + 52
2  Foundation                     0x3b67c __NSThreadPerformPerform + 192
3  CoreFoundation                 0xb3468 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
4  CoreFoundation                 0xc3598 __CFRunLoopDoSource0 + 204
5  CoreFoundation                 0x5774 __CFRunLoopDoSources0 + 256
6  CoreFoundation                 0xae48 __CFRunLoopRun + 768
7  CoreFoundation                 0x1e194 CFRunLoopRunSpecific + 572
8  Foundation                     0x17eac -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
9  MyApp                 0x2c1200 +[BeaconAsyncSocket cfstreamThread] + 3868696
10 Foundation                     0x64bdc __NSThread__start__ + 792
11 libsystem_pthread.dylib        0x3348 _pthread_start + 116
12 libsystem_pthread.dylib        0x1948 thread_start + 8

**Comment by wangbo1185742894** [comment]
这个问题 最新版sdk已经修复，或者你这里可以使用不含灯塔的sdk  QCloudCOSXML/Slim（这个错误是灯塔sdk导致的）
