### ISSUE TITLE
SPM 编译问题

### ISSUE THREAD

**Issue by RayJiang16** [tencentyun/qcloud-sdk-ios#57]
由于项目依赖需要改用 SPM 管理，在自建 GitLab上 创建了 SPM，发现 QCloudCOSXML 框架部分文件由于缺少 import 导致无法编译通过。
使用当前最新版本 v6.2.5，发现 NS_ENUM 相关的文件缺少 #import <Foundation/Foundation.h>，涉及文件如下：
- GenerateSnapshotFormat.h
- GenerateSnapshotMode.h
- GenerateSnapshotRotateType.h
- COSIncludedObjectVersions.h
- IntelligentTieringStatus.h
- InventoryStatue.h
- COSXMLCompressionType.h
- ExpressionType.h
- InputFileHeaderInfo.h
- InputJSONFileType.h
- OutputQuoteFields.h

以上文件列表取的是代码注释第二行，实际文件有部分已经改名。

另外咨询一下，是否有支持 SPM 的计划？

**Comment by wangbo1185742894** [comment]
github的demo可以正常编译运行吗？

**Comment by RayJiang16** [comment]
Demo 使用 Pod 依赖方式编译不会报错，我是在自建 GitLab 上支持 SPM 后发现有 import 缺失问题

**Comment by RayJiang16** [comment]
期望是麻烦你们补全一下 import，现在我们每次将代码从 GitHub 更新到 GitLab 都需要手动给这几个文件加 import

**Comment by wangbo1185742894** [comment]
方便加一下qq吗？具体说说要怎么补，补完之后 下个版本体现。qq:1185742894

**Comment by houseme** [comment]
> 方便加一下qq吗？具体说说要怎么补，补完之后 下个版本体现。qq:1185742894

有大概的时间节点吗？

**Comment by freezy7** [comment]
#60 这边我临时支持了下，可以直接使用，可以试试这种方法
