### ISSUE TITLE
图片上传报错

### ISSUE THREAD

**Issue by hanzhuzi** [tencentyun/qcloud-sdk-ios#6]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？

* 您使用的SDK版本好是多少？

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]

* 使用更高版本的SDK是否解决了您的问题？

* 这个问题是否和特定的网络环境有关系？

* 您集成我们SDK的方式是什么？

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

腾讯云COS，5.4.4， 报 QCloudPutObjectRequest][3336]当前网络环境为1 请求失败Error Domain=NSURLErrorDomain Code=-1003 "未能找到使用指定主机名的服务器。" UserInfo={NSUnderlyingError=0x110fceac0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=http://teazhi-1253753824-appid.cos.(null).myqcloud.com/c08660ac012420c8f2fbdcb4c474df4afad8dda22997aba5d8b9b012008e7e05.jpeg, NSErrorFailingURLKey=http://teazhi-1253753824-appid.cos.(null).myqcloud.com/c08660ac012420c8f2fbdcb4c474df4afad8dda22997aba5d8b9b012008e7e05.jpeg, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=未能找到使用指定主机名的服务器。}

**Comment by EricCheungSCUT** [comment]
初始化时候 regionName 没有填

**Comment by EricCheungSCUT** [comment]
参考 [初始化](https://cloud.tencent.com/document/product/436/11280#1.-.E5.88.9D.E5.A7.8B.E5.8C.96) 时候，需要设置 endpoint.regionName = @"服务地域名称"

**Comment by EricCheungSCUT** [comment]
这边还看到有个问题就是，请求填写 bucket 时候，在这个 case 中填 teazhi-1253753824 即可，这就对应着我们文档中的 <bucket>-<appid> 的形式了，而不是 teazhi-1253753824-appid

**Comment by EricCheungSCUT** [comment]
Close because of inactive for a long time
