### ISSUE TITLE
可否提供xcframework

### ISSUE THREAD

**Issue by Gaozn** [tencentyun/qcloud-sdk-ios#60]
可否提供xcframework

**Comment by wangbo1185742894** [comment]
目前还在计划中。sdk提供了源码，支持用户自行打包。

**Comment by freezy7** [comment]
我做了一个同时支持xcframwork和SPM的项目，可以直接使用，或者参考项目文档上的介绍自己制作个
项目地址：[https://github.com/freezy7/QCloudCOSXML](https://github.com/freezy7/QCloudCOSXML)

步骤：

**Comment by freezy7** [comment]
> 目前还在计划中。sdk提供了源码，支持用户自行打包。

期待尽快支持M1芯片arm64模拟器的指令集的framework

**Comment by wangbo1185742894** [comment]
已提供xcframework打包脚本，可自行打包。
