### ISSUE TITLE
可否修复以下的编译问题重新提供framework

### ISSUE THREAD

**Issue by kchann123** [tencentyun/qcloud-sdk-ios#61]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
上传对象

* 您使用的SDK版本好是多少？
6.3.9

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]

* 使用更高版本的SDK是否解决了您的问题？
否

* 这个问题是否和特定的网络环境有关系？
否

* 您集成我们SDK的方式是什么？
framework集成

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

<img width="921" alt="截屏2024-05-15 08 51 10" src="https://github.com/tencentyun/qcloud-sdk-ios/assets/169861986/3e52ce00-b7f5-46dd-ba4e-79c6ede06ff2">

<img width="920" alt="截屏2024-05-15 08 53 47" src="https://github.com/tencentyun/qcloud-sdk-ios/assets/169861986/bab04708-b1c4-4e72-9aa9-ca432fa80229">

**Comment by wangbo1185742894** [comment]
感谢反馈，下个版本修一下，目前应该不影响使用。

**Comment by wangbo1185742894** [comment]
6.4.0版本已修复
