### ISSUE TITLE
SDK从6.3.8升级为6.3.9编译报错

### ISSUE THREAD

**Issue by Merlini93** [tencentyun/qcloud-sdk-ios#62]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
QCloudCOSXML/Transfer
* 您使用的SDK版本好是多少？
6.3.9
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机/iOS17.5.1 MacOS 14.5 Xcode15.4
* 使用更高版本的SDK是否解决了您的问题？
否
* 这个问题是否和特定的网络环境有关系？
否
* 您集成我们SDK的方式是什么？
cocoapods
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
使用cocoapods将SDK从6.3.8升级为6.3.9之后，编译报错，具体如图：
<img width="367" alt="image" src="https://github.com/tencentyun/qcloud-sdk-ios/assets/11328707/98f47bf5-9ac5-485e-9242-08b040f2f6da">
<img width="481" alt="image" src="https://github.com/tencentyun/qcloud-sdk-ios/assets/11328707/b803021a-dc41-4413-9dc1-97b48060430a">

编译器无法定位错误，尝试解决未果。
降级为6.3.8报错消失。
希望修复此bug，否则无法集成最新版SDK。

**Comment by wangbo1185742894** [comment]
重新pod以下 试试？我这里测试可以编译通过呢

**Comment by Merlini93** [comment]
> 重新pod以下 试试？我这里测试可以编译通过呢

重新pod过了，还是会报错。我也奇怪，我新建项目是可以编译通过的，但是老项目中升级6.3.9就会报错

**Comment by wangbo1185742894** [comment]
新建项目 用6.3.9可以编译通过？

**Comment by Merlini93** [comment]
是的。

**Comment by wangbo1185742894** [comment]
试试 先把cos sdk移除 ，再加进去呢

**Comment by Merlini93** [comment]
也不行

**Comment by Merlini93** [comment]
<img width="576" alt="image" src="https://github.com/tencentyun/qcloud-sdk-ios/assets/11328707/760a92bf-3383-47e5-8432-64fefd8b9c36">
我试了一下，将QCloudUploadObjectResult.h里面QCloudUploadCallbackError类下面的属性Message改为message，变成小写项目就不报错了，可能是这个属性名跟其他sdk里面冲突了，或者是跟系统属性名冲突了？

**Comment by Merlini93** [comment]
我更怀疑是跟系统的属性名冲突了，因为集成的别的SDK里面也有许多属性名是message的。

**Comment by wangbo1185742894** [comment]
看看项目里有没有给NSObject些分类，然后分类里定义了 Message
