### ISSUE TITLE
iOS 18 运行报错

### ISSUE THREAD

**Issue by 1051390159** [tencentyun/qcloud-sdk-ios#64]
目前使用的SDK为 6.4.1版本，使用真机运行报以下错误

<img width="536" alt="image" src="https://github.com/user-attachments/assets/29221348-4d6e-4baf-881a-3351beed4e69">
<img width="710" alt="image" src="https://github.com/user-attachments/assets/28b98abe-73af-42e3-9cbc-8e7adc00044a">

**Comment by wangbo1185742894** [comment]
iOS 18 bate版本么？

**Comment by 1051390159** [comment]
> iOS 18 bate版本么？

是的

**Comment by wangbo1185742894** [comment]
预计下周一发布6.4.3版本，修复这个问题。

**Comment by crasowas** [comment]
@wangbo1185742894 `QCloudQuic`需要发布新版本，当前最新的`6.3.9`版本没有修复这个问题

**Comment by wangbo1185742894** [comment]
Qcloudquic和qcloudcosxml没有依赖关系，qcloudquic可以继续使用6.3.9，qcloudcosxml可以升级到6.4.4
