### ISSUE TITLE
isProxyUsed在macOS上报错

### ISSUE THREAD

**Issue by Joburgess** [tencentyun/qcloud-sdk-ios#65]
isProxyUsed在macOS上报错

Last Exception Backtrace:
0   CoreFoundation                           0x186e84534 __exceptionPreprocess + 164
1   libobjc.A.dylib                          0x186975eb4 objc_exception_throw + 60
2   CoreFoundation                           0x186f36124 -[NSObject(NSObject) __retain_OA] + 0
3   CoreFoundation                           0x186dee764 ___forwarding___ + 1572
4   CoreFoundation                           0x186dee080 _CF_forwarding_prep_0 + 96
5   Runner                                   0x102b64ef0 -[QCloudTrackNetworkUtils isProxyUsed] + 72
6   Runner                                   0x102b662a8 -[QCloudTrackService getCommonParams] + 508
7   Runner                                   0x102b65b70 -[QCloudTrackService init] + 96
8   Runner                                   0x102b65af8 __35+[QCloudTrackService singleService]_block_invoke + 24
9   libdispatch.dylib                        0x186b80910 _dispatch_client_callout + 20
10  libdispatch.dylib                        0x186b8214c _dispatch_once_callout + 32
11  Runner                                   0x102b65adc +[QCloudTrackService singleService] + 60
12  Runner                                   0x102b62180 +[QualityDataUploader trackBaseInfoToTrachCommonParams:] + 464
13  Runner                                   0x102a875a4 +[QCloudCOSXMLService(Quality) initMTA:] + 152
14  Runner                                   0x102a874f0 +[QCloudCOSXMLService(Quality)

**Comment by wangbo1185742894** [comment]
已修复，麻烦升级到最新版本
