### ISSUE TITLE
什么时候SDK适配一下Apple M系列芯片

### ISSUE THREAD

**Issue by wtdu** [tencentyun/qcloud-sdk-ios#66]
目前只要项目集成相关sdk ，只能用真机或者 rosetta 模式模拟器运行，很不方便，而且 rosetta模式有很多问题，是否可以考虑sdk适配一下M系列架构

**Comment by wangbo1185742894** [comment]
是pod集成的 还是framework集成

**Comment by wtdu** [comment]
目前项目使用swift pakage manager 包管理，但是贵司的sdk 不支持spm ，所以 暂时手动导入framework 的，没有使用pod

**Comment by wtdu** [comment]
主要是现在集成QCloid 相关的 framework 后， xcode 简单的  view preview 操作都会报错，就是因为在M系列芯片上编译不通过导致，是否可以赶快解决下这个问题 @wangbo1185742894

**Comment by wtdu** [comment]
> > @wangbo1185742894 目前项目使用swift pakage manager 包管理，但是贵司的sdk 不支持spm ，所以 暂时手动导入framework 的，没有使用pod
> 
> 请问手动集成是怎么集成的，我手动集成SDK，各种undefined symbol
@chenanghui 
就把 framework 下载下来 引入工程，然后参考文档 该配置的选项加一下就可以了，你是用模拟器报错了吧，framework 不支持 M系列模拟器，你用真机试一试应该能跑起来，如果用模拟器，需要用rosetta 模式，具体可以自行搜一搜怎么切换rosetta 模式

**Comment by wangbo1185742894** [comment]
@chenanghui 按照官网文档手动集成应该不会有问题，只是需要真机或者模拟器rosetta模式。

**Comment by wangbo1185742894** [comment]
@wtdu framework支持m系列芯片，在规划中

**Comment by aijun198600** [comment]
顶一下，RN的版本也是，基础版本相对firebase差太远了

**Comment by wangbo1185742894** [comment]
> 顶一下，RN的版本也是，基础版本相对firebase差太远了

rn最新版本 1.1.4，一来iOS cos  sdk 6.4.3。也不算差太远吧

**Comment by jordanqin** [comment]
@aijun198600 是说rn cos sdk依赖的react native版本太低吗？你们期望升级到哪个版本呢？我们评估下，毕竟也是需要考虑rn低版本用户的

**Comment by wangbo1185742894** [comment]
已提供xcframework打包脚本，可自行打包。
