### ISSUE TITLE
请问下精简版目前最新只能更新到6.4.2么？如何更新到6.4.3以上解决xcode16编译报错问题？

### ISSUE THREAD

**Issue by SmallHuang-ray** [tencentyun/qcloud-sdk-ios#67]
我目前使用的ios得劲精简版，直接pod更新，只能更新到6.4.2，无法更新到已经修复了xcode16编译报错的6.4.3及以上版本，请问目前精简版是没有更新最新版本还是说我的方法不对？我是直接pod指定pod 'QCloudCOSXML/Transfer'到6.4.3报错说无法更新~

**Comment by wangbo1185742894** [comment]
最新版本6.4.4，尝试升级一下cocoapod
