### ISSUE TITLE
 libstdc++ was removed from iOS12, XCode10 cant't build it

### ISSUE THREAD

**Issue by MontFei** [tencentyun/qcloud-sdk-ios#7]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？

* 您使用的SDK版本好是多少？

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]

* 使用更高版本的SDK是否解决了您的问题？

* 这个问题是否和特定的网络环境有关系？

* 您集成我们SDK的方式是什么？

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

**Comment by EricCheungSCUT** [comment]
Currently this can be solved by [adding libstdc++ manually in Xcode 10](https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9). Stripping dependency for libstdc++ from our framework needs to be evaluated and might take some time.  We will take this as a feature request.
