### ISSUE TITLE
[__NSArray0 qcloud_modelToJSONData]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by PatrickChow** [tencentyun/qcloud-sdk-ios#8]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
万象优图
* 您使用的SDK版本好是多少？
最新的5.4.6
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
iPhoneX，iOS 11.3， Wi-Fi
* 使用更高版本的SDK是否解决了您的问题？

* 这个问题是否和特定的网络环境有关系？

* 您集成我们SDK的方式是什么？
通过 cocoapods 
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

   最新版本cocoapods 使用 use_frameworks! 之后，所有被写到分类里的校验方法报错
比如地区判断 [NSString matchesRegularExpression]
找不到该方法

**Comment by EricCheungSCUT** [comment]
可否提供一下cocoapods的版本？

**Comment by PatrickChow** [comment]
1.5.3

**Comment by EricCheungSCUT** [comment]
看一下工程设置里面的 other Linker flags 里有 -ObjC 选项吗，没有的话手动加上去试一下
